
import static javafx.application.Application.launch;
import java.io.*;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author admin
 */
public class welcomepage extends javax.swing.JPanel {

    /**
     * Creates new form welcomepage
     */
    public welcomepage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        jButton1 = new javax.swing.JButton();

        setLayout(null);

        label1.setText("Welcome to Bay Area Trafic");
        add(label1);
        label1.setBounds(197, 25, 174, 20);

        label2.setText("A game where instead of relaxing you stress");
        add(label2);
        label2.setBounds(150, 50, 290, 50);

        jButton1.setText("Start Game");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(220, 130, 112, 29);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        //jPanel jPanel5 = new jPanel;  
        this.setVisible(false);
        new The_Board().setVisible(true);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    public static void main(String[] args) {
        //launch(args);
        //java.awt.EventQueue.invokeLater(new Runable(){
        
        //@Override;
        //public void run(){
            //new welcomepage().setVisible(true);
        //}} );
        
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private java.awt.Label label1;
    private java.awt.Label label2;
    // End of variables declaration//GEN-END:variables
}
